openapi: 3.0.0
paths:
  /api/login:
    post:
      operationId: LoginController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInUserDto"
      responses:
        "200":
          description: ログイン完了
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponseDto"
info:
  title: API description
  description: ""
  version: "1.0"
  contact: {}
tags: []
servers:
  - url: /
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    SignInUserDto:
      type: object
      properties:
        email:
          type: string
          example: user1@test.com
        password:
          type: string
          example: password
      required:
        - email
        - password
    UserEntity:
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: ユーザー1
          minLength: 2
          maxLength: 25
        email:
          type: string
          example: user1@test.com
          maxLength: 255
        email_verified_at:
          format: date-time
          type: string
          example: "2022-10-28T08:38:14.237Z"
        password:
          type: string
          example: password
        remember_token:
          type: string
          example: remember_token
        createdAt:
          format: date-time
          type: string
          example: "2022-10-28T08:38:14.237Z"
        updatedAt:
          format: date-time
          type: string
          example: "2022-10-28T08:38:14.237Z"
      required:
        - id
        - name
        - email
        - password
        - createdAt
        - updatedAt
    AuthResponseDto:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            name:
              type: string
              example: ユーザー1
            token:
              type: string
              example: 3|gp3F2vTrNwdY5AgZVdkPfk22xHErjwmGpRT93yEO0c026938
        message:
          type: string
          example: User login successfully.
      required:
        - success
        - data
        - message
